/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Specs {
  'movement' : string,
  'caseSize' : string,
  'strap' : string,
  'waterResistance' : string,
  'crystal' : string,
  'material' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Watch {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'specs' : Specs,
  'category' : string,
  'brand' : string,
  'image' : string,
  'price' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWatch' : ActorMethod<
    [string, string, string, bigint, string, string, Specs],
    Watch
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteWatch' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatch' : ActorMethod<[bigint], [] | [Watch]>,
  'getWatches' : ActorMethod<[], Array<Watch>>,
  'initializeWatchesIfEmpty' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateWatch' : ActorMethod<
    [bigint, string, string, string, bigint, string, string, Specs],
    Watch
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];